### ISSUE TITLE
Initial alpha test release

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argodmqc_owc#2]
Hi,
I've rushed a little bit yesterday when migrating the repo
I think we should tag a release 0.1.0 with the initial state, the version that is being tested by expert users.
So I propose to strip the code from my commits yesterday, and tag a release with this initial state
It should be easier to work with for debugging the testers
Are you ok @edsmall-bodc @matdon17 ?

**Comment by edsmall-bodc** [comment]
Sounds good to me. Let me know when you've rolled it back.

**Comment by gmaze** [comment]
Ok, I created the release v0.1.0 at the state  where it was when I migrated the repo from NOC to Github (commit bf75edcee4f52fbf2162971a8718fdd4c3d03faf).

So to get the code as it was, you can:
```bash
git checkout v0.1.0
```

**Comment by gmaze** [comment]
Ok, so now the repo "master" branch is back to its "initial" state (tagged v0.1.0).

I will push my updates (better readme and binder integration) to a PR.

**Comment by gmaze** [comment]
I'll do a specific PR for CI on Github actions that was not on v0.1.0
