### ISSUE TITLE
Software LICENSE

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argodmqc_owc#24]
Which license should we use ?

This can help: https://choosealicense.com/

https://github.com/euroargodev/argodmqc_owc/pull/25

**Comment by edsmall-bodc** [comment]
I think probably https://choosealicense.com/licenses/gpl-3.0/

We want to encourage people to share and use the code (for free, of course), and we also welcome changes to the code - but these changes should be suggested to use and made here by a PR. this makes sure that the changes/improvements are available to everybody.

@matdon17 ?

**Comment by matdon17** [comment]
@apswong and @cabanesc should this match the license used with the Matlab version?  Currently:
https://github.com/ArgoDMQC/matlab_owc/blob/master/LICENSE
