### ISSUE TITLE
Problem in selecting Argo referenced data

### ISSUE THREAD

**Issue by kamwal** [euroargodev/argodmqc_owc#30]
Durring running the OWC analysis using Argo referenced data only, I encountered the below error:

` UPDATE_SALINITY_MAPPING: Working on profile  3
Traceback (most recent call last):
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\get_region\get_region_data.py", line 172, in get_region_data
    grid_long = wrap_longitude(grid_long)
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\get_region\data_functions\wrap_longitude.py", line 27, in wrap_longitude
    neg_long = np.argwhere(grid_long < 0)
TypeError: '<' not supported between instances of 'list' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_SSH/owc-software-python/owc_calibration.py", line 73, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\update_salinity_mapping\update_salinity_mapping.py", line 330, in update_salinity_mapping
    best_hist_lat, best_hist_long, best_hist_dates] = get_region_data(wmo_numbers,
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\get_region\get_region_data.py", line 198, in get_region_data
    raise Exception("NO DATA FOUND")
Exception: NO DATA FOUND

Process finished with exit code 1

`
In running the same analysis for (1) ctd+ argo and (2) CTD only, there was not such error.

FLOAT SOURCE NUMBER: 3901960
REFERENCE DATA: ARGO_for_DMQC_2020V01.mat
WMO boxes: wmo_boxes_argo.mat 
OBJECTIVE MAPPING PARAMETERS:

`       # ===============================
        #
        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 2,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 1,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.02,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 10,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 100,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 200`

**Comment by edsmall-bodc** [comment]
Duplicate of https://github.com/euroargodev/argodmqc_owc/issues/32

**Comment by edsmall-bodc** [comment]
This is not a duplicate - one crash occurs whilst fetching data (this one). The other crashed occurs whilst interpolating.

**Comment by edsmall-bodc** [comment]
@kamwal Can you attach your float_source to this issue please?

**Comment by kamwal** [comment]
Yes, sure. 
[source_3901960.zip](https://github.com/euroargodev/argodmqc_owc/files/4901288/source_3901960.zip)

**Comment by edsmall-bodc** [comment]
So you ran this for just Argo data?

**Comment by kamwal** [comment]
yes, I was using only  Argo reference data here.

ARGO_for_DMQC_2020V01
WMO_BOXES: wmo_boxes_argo.ma

**Comment by gmaze** [comment]
It's probably still too early, but argopy is able to fetch and return data from the Argo reference dataset !

```python
from argopy import DataFetcher as ArgoDataFetcher
loader = ArgoDataFetcher(src='erddap', ds='ref')
ds1 = loader.region([-85, -45, 10, 20, 0, 1000, ‘2012-01’, ‘2012-02’]).to_xarray()
```
we could develop an access point that would work with owc, ie using distances instead of a rectangular space/time domain

**Comment by matdon17** [comment]
Shall we make this another ticket for an enhancement?

**Comment by gmaze** [comment]
yes, that would be more specific and help us get what is really required by pyowc

**Comment by kamwal** [comment]
The fix to issue of reading Argo reference data is in branch `https://github.com/euroargodev/argodmqc_owc/tree/kamwal/argo_ref`

The issue of not reading these data was associated with use of the os.path.sep.join which was not correctly joining the parts of the string of directory where the Argo data were stored.

The branch is also fixing issue of not read WMO boxed by scipy.io loadmat python function that was not able to read .mat data with version of 7.4.

**Comment by kamwal** [comment]
This issue has been fixed using the [fix](https://github.com/euroargodev/argodmqc_owc/pull/52)
