### ISSUE TITLE
SAF and PV code

### ISSUE THREAD

**Issue by edsmall-bodc** [euroargodev/argodmqc_owc#39]
Most of the code for the Potential Vorticity has actually been merged in (though I do need to double check this). However, we still need to merge in the code that allows an operator to filter out data around the South Antarctic Front.

**Comment by kamwal** [comment]
The initial checks of the PV parameter in Python code showed that code is working well. 
I used float example from the SA, however, a better example to show it would be from the SPG in the NA. In running a few example codes from NA I hit the base decored issue that is already fixed but not yet merged to the master branch. 

The example from Python for left PV=0 and right PV=1 (MAPSCALE_PHI_LARGE=0.1, MAPSCALE_PHI_SMALL=0.02)
![image](https://user-images.githubusercontent.com/57108044/92223276-2582f300-ee98-11ea-99a4-77e515d2a0cf.png)

The comparison with Matlab output for this float showed very similar results to Python version.
![image](https://user-images.githubusercontent.com/57108044/92223892-05076880-ee99-11ea-8570-5c41f3ad7b1c.png)

**Comment by kamwal** [comment]
Additionally. in running the code in Python with PV=1 I found that this parameter needs to be set in two places in start_with_pycharm.py and in the configuration.py. I think that placing PV in start_with_pycharm aimed to keep all the key parameters to change in one place. I think this step needs to be corrected/finished. 

![image](https://user-images.githubusercontent.com/57108044/92224747-26b51f80-ee9a-11ea-807b-acc2a7582d8c.png)

![image](https://user-images.githubusercontent.com/57108044/92224816-42202a80-ee9a-11ea-8460-844a97b6e2f5.png)

Also in the evaluation of the Python code with PV=1 the code is displaying many rows with the MAPSCALE_PHI_LARGE and  MAPSCALE_PHI_SMALL specification. This also needs to be corrected.
![image](https://user-images.githubusercontent.com/57108044/92225328-f5891f00-ee9a-11ea-9cd5-5b60ef0e0f51.png)

**Comment by Teddyzander** [comment]
Hi @kamwal,

It doesn't need to be set in two places. What you see in the start_with_pycharm code is an example of how you can change the contents of your configuration set up "mid run", if you want.

The variable USER_CONFIG is a dictionary containing all the set up parameters you see in the configuration.py file. If you want to change a parameter, you have two options

1. Change the parameter in the config file
2. Set the key in the USER_CONFIG variable to the new value

You are seeing (2) when the code says `USER_CONFIG['MAP_USE_PV'] = 1`

**Comment by Teddyzander** [comment]
It is worth noting here that step (2) overrides step (1).

If you wish you can even make another variable containing the user_config, make edits to that, and then use that for a run too.

This is so that you can use multiple configurations in a single run. You can then save the outputs differently and compare them for different configs.

**Comment by kamwal** [comment]
The SAF code is included in branch [argodmqc_owc/tree/kamwal/SA](https://github.com/euroargodev/argodmqc_owc/tree/kamwal/SAF)
It will be merged after fixing issue [argodmqc_owc/issues/39](https://github.com/euroargodev/argodmqc_owc/issues/39])

**Comment by kamwal** [comment]
The fix has been merged to master branch [git merge](https://github.com/euroargodev/argodmqc_owc/pull/51)
