### ISSUE TITLE
Migrating repo from NOC to EUROARGODEV

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argodmqc_owc#5]
In order to migrate the repository from NOC to github servers at EUROARGODEV:

## Requirements:
- [x] Check if the [Github import tool](https://github.com/new/import) is effective. @gmaze tested it with success at https://github.com/gmaze/owc-software-python. All repo history and contributions are imported properly (see [contributions here](https://github.com/gmaze/owc-software-python/graphs/contributors) and [commits here](https://github.com/gmaze/owc-software-python/commits/master)).
- [x] Check if the [CI workflow for NOC](https://git.noc.ac.uk/bodc/owc-software-python/pipelines) can be managed with github actions (or other service like [Travis](https://travis-ci.org/)). @gmaze tested with success an implementation of [NOC workflow in a Github actions](https://github.com/gmaze/owc-software-python/blob/master/.github/workflows/main.yml). Online testing is run with success ([See here for instance](https://github.com/gmaze/owc-software-python/actions/runs/115668971)) under Linux and Mac OS and with python versions 3.6, 3.7 and 3.8 (which seems to be more than what was done at NOC). However, it is unsuccessful under Windows OS, which should be fixed later.

## Migration procedure:
- [x] Run the [Github import tool](https://github.com/new/import)
- [x] Check history of commits, branch merging, etc ...
- [x] Move "merge_request_templates" to .github folder
- [x] Add a Github action workflow for CI, following @gmaze [template here](https://github.com/gmaze/owc-software-python/blob/master/.github/workflows/main.yml).
- [x] Link repo to https://codecov.io/gh/euroargodev and set-up code coverage (which is excellent here !) reporting
- [x] Link repo to https://requires.io/ and set-up requirements checks
- [x] Add readme and badges
- [x] Set-up Access rights

@edsmall-bodc, @matdon17 : I'll be happy to do this if you want me to.

**Comment by gmaze** [comment]
@edsmall-bodc , why would you wait ? this is simply a better display of what was done to the code for migrating to github and adding CI with Actions.

**Comment by edsmall-bodc** [comment]
@gmaze I'm not "waiting", I'm just busy sorting something else out at the moment. Phase 2 is due to start next week (probably mid-week), and I just need to be sure that everything is ready for this phase (my priority).

This requires a review on my part, and it uses some things that I haven't used before. I was planning on reviewing it this weekend and checking out the new stuff you have added properly. I know what it does, but I want to know how it works before I merge it into the master.

If all is well, I would merge it in on Monday.

**Comment by gmaze** [comment]
sorry, I didn't meant that you're not busy with other things !
