### ISSUE TITLE
float_source matlab files incorrect

### ISSUE THREAD

**Issue by gmaze** [euroargodev/argodmqc_owc#73]
While working on euroargodev/argopy/issues/141 and euroargodev/argopy/pull/142 I found that the following pyowc float_source matlab files:
- https://github.com/euroargodev/argodmqc_owc/blob/master/data/float_source/3901960.mat
- https://github.com/euroargodev/argodmqc_owc/blob/master/data/test_data/float_source/3901960.mat

are incorrect !

They appear to have been generated with an old version of the Matlab routine create_float_source.m.
The last version uses another method to sub-select vertical pressure levels (floor instead of round), 
It can be seen here: https://github.com/euroargodev/dm_floats/commit/74978742323fe8fb77c96c0a819e1c5523e5c422#diff-a7f153565065c547918a043959d1efd54b042a8d75edbf7fcef1c8bd6f76ec72

So I guess these files must be updated
The most recent version of the create_float_source.m routine is here:
https://github.com/euroargodev/dm_floats/blob/master/src/ow_source/create_float_source.m

**Comment by kamwal** [comment]
yes, we used the previous version of the float_source code. I am going to regenerate this file and update the example in the branch

**Comment by kamwal** [comment]
the source data and source data have been updated using the new routine
https://github.com/euroargodev/dm_floats/blob/master/src/ow_source/create_float_source.m
